spring:
  data:
    redis:
      host: 47.79.85.176
      port: 6379
      database: 0
minio:
  endpoint: http://http://47.79.85.176:9000
  access-key: asluax
  secret-key: abc350587745
  bucket-name: lease